cc_library(
    name = "camera_interface",
    hdrs = ["camera_interface.hpp"],
    deps = [
        "//core/mat:mat",
    ],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "color_conversion",
    srcs = ["color_conversion.cpp"],
    hdrs = ["color_conversion.hpp"],
    deps = [
        "//core/mat:mat",
    ],
    visibility = ["//visibility:public"]
)
