cc_library(
    name = "color_conversion",
    srcs = ["color_conversion.cpp"],
    hdrs = ["color_conversion.hpp"],
    deps = [
        "//core/mat:mat",
        "@abseil-cpp//absl/log:log",
    ],
    visibility = ["//visibility:public"]
)
