cc_library(
    name = "load_bazel_runfile",
    hdrs = ["load_bazel_runfile.hpp"],
    deps = [
        "@abseil-cpp//absl/log:log",
        "@rules_cc//cc/runfiles",
    ],
    visibility = ["//visibility:public"],
)
