cc_test(
    name = "mat_test",
    srcs = ["mat_test.cpp"],
    deps = [
        "//core/mat:mat_io",
        "//core/mat:mat",
        "//core/mat:mat_cc_proto",
        "@catch2//:catch2_main"
    ],
)
